name: fvc_composition
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - gdal
  - rasterio
  - geopandas
  - scikit-learn
  - pdal
  - matplotlib
  - numpy<2.0
  - pandas
  - scipy
  - seaborn
  - jupyterlab
  - ipykernel
  - tqdm
  - pyyaml
  - pytorch-lightning
  - tensorboard
  - scikit-image
  - ipympl
  - pillow
  - protobuf
  - pyproj
  - pip:
    - anywidget==0.6.5
    - iterative-stratification==0.1.9
    - leafmap==0.35.11
    - lonboard==0.3.0
    - opencv-python==4.11.0.86
    - palettable==3.3.3
    - pyarrow==13.0.0
    - python-dotenv==1.0.1
    - torch-summary==1.4.5
    - triton==2.2.0
    - nvidia-ml-py3
    - albumentations
    - open3d

# variables:
#   PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cu118
# prefix: /home/laura/miniconda3/envs/fvc_composition
